### PR TITLE
[MWPW-158446] Added stage domains map

### PR DESCRIPTION
**Pull request by robert-bogos**
This PR adds the `stageDomainsMap`, enabling the conversion of production URLs to their stage equivalents in the stage environment.
More details about this feature can be found in [this discussion](https://github.com/orgs/adobecom/discussions/2880).

Resolves: [MWPW-158446](https://jira.corp.adobe.com/browse/MWPW-158446)

**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.live?martech=off
- After: https://mwpw-158446-domains-map--bacom--adobecom.hlx.live?martech=off

### CODE REVIEW

**Review by meganthecoder — COMMENTED** [review]
Will this differentiate between `business.adobe.com` and `business.adobe.com/blog/`? Because they have different hlx urls

**Comment by robert-bogos** [comment]
Hi @meganthecoder ! 
No, it won’t differentiate between those because the difference lies in the URL path, not the domain. We’re only comparing domains using the map.

We might need a future enhancement to also handle this use-case.

**Comment by meganthecoder** [comment]
> Hi @meganthecoder ! No, it won’t differentiate between those because the difference lies in the URL path, not the domain. We’re only comparing domains using the map.
> 
> We might need a future enhancement to also handle this use-case.

@robert-bogos This will cause issues with bacom blog links on hlx.page and hlx.live. For example:

1. Go to https://mwpw-158446-domains-map--bacom--adobecom.hlx.live/
2. Click on "Resources" in the gnav
3. Click on "Experience Cloud blog"

This will take you to: https://mwpw-158446-domains-map--bacom--adobecom.hlx.live/blog/ which will 404 because the bacom blog is on `--bacom-blog--adobecom.hlx.live` not `--bacom--adobecom.hlx.live`.

CC @narcis-radu @Dli3 @JasonHowellSlavin @Brandon32

**Comment by narcis-radu** [comment]
@meganthecoder - I see this is a very particular use-case which hasn't been requested in the initial ticket. Is it possible to handle this as fast follow-up and unblock testing?

**Comment by robert-bogos** [comment]
The solution I see is to configure the current map to only convert links on business.stage.adobe.com and not on .hlx.live or .hlx.page. In this way testing is possible on stage and we won't have issues on .live and .page. 
We can come with a future enhancement to handle those particular use-cases.
@narcis-radu @meganthecoder

**Review by meganthecoder — APPROVED** [review]

**Review by sukamat — APPROVED** [review]

**Review by JasonHowellSlavin — APPROVED** [review]

**Review by Brandon32 — APPROVED** [review]
Please squash your commits

**Pull request merged**
