### PR TITLE
MWPW-129288 Customer Stories ROW Sitemap

### PR DESCRIPTION
**Pull request by meganthecoder**
* Setup sitemap for Customer Success Stories ROW

Resolves: [MWPW-129288](https://jira.corp.adobe.com/browse/MWPW-129288)

**Test URLs:**
N/A

### CODE REVIEW

**Review by fullcolorcoder — COMMENTED** [review]
I'd recommend adding a sitemap-index.xml for a source of truth. Example: https://github.com/adobecom/fedpub/blob/main/sitemap-index.xml

**Comment by meganthecoder** [comment]
> I'd recommend adding a sitemap-index.xml for a source of truth. Example: https://github.com/adobecom/fedpub/blob/main/sitemap-index.xml

@fullcolorcoder The sitemap list for bacom is coming from AEM. Will adding a sitemap to milo interfere with that?

**Comment by fullcolorcoder** [comment]
@meganthecoder Possibly, yes. Those would 404 when crawled now, which isn't great obviously. Perhaps it would be best to either match those paths, or have them change those paths to match yours. 

It could also be a good idea to have them sunset parts of that robots.txt and add it to the individual projects. https://main--bacom--adobecom.hlx.page/robots.txt for example can be overridden, but looks like it'd need compensated for in origin paths.

**Comment by meganthecoder** [comment]
We're closing this ticket, and we'll create a new ticket once the SEO team provides full requirements.

**Pull request closed without merging**
