### PR TITLE
MWPW-119015 Text List Styles

### PR DESCRIPTION
**Pull request by meganthecoder**
* Add custom "text list" styles for text block to satisfy webinar requirements

Resolves: [MWPW-119015](https://jira.corp.adobe.com/browse/MWPW-119015)

**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/methomas/event-speakers?martech=off
- After: https://methomas-text-list--bacom--adobecom.hlx.page/drafts/methomas/event-speakers?martech=off

### CODE REVIEW

**Comment by meganthecoder** [comment]
I don't think it's great to add block-specific styles to the styles.css file that'll be added to every page. However, I thought that since the styling was fairly small, this would be more performant that having js logic that would load styles if the block existed. This also came up with the comparison table but ultimately it needed to be a new block for different reasons. This may continue to come up and we can re-evaluate then if necessary

**Review by JasonHowellSlavin — APPROVED** [review]
LGTM.

**Comment by ryanmparrish** [comment]
@meganthecoder I think this works. I agree w/ your thoughts around including this in base styles being a little over scoping. 
Aside from the max-width on desktop, you can get [very close](https://main--bacom--adobecom.hlx.page/drafts/parrish/event-speakers) to this just using the (small) variant and maybe adding an override for the text.small margin. 
`.text-block.small p, .text-block.small [class^="body-"] { margin: var(--spacing-xxs) 0; }` IDK
Screen Shot 2022-11-22 at 11 02 07 AM

Im good w/ this approach. just some food for thought if we need to revisit later.

**Comment by meganthecoder** [comment]
> @meganthecoder I think this works. I agree w/ your thoughts around including this in base styles being a little over scoping. Aside from the max-width on desktop, you can get [very close](https://main--bacom--adobecom.hlx.page/drafts/parrish/event-speakers) to this just using the (small) variant and maybe adding an override for the text.small margin. `.text-block.small p, .text-block.small [class^="body-"] { margin: var(--spacing-xxs) 0; }` IDK Screen Shot 2022-11-22 at 11 02 07 AM
> 
> Im good w/ this approach. just some food for thought if we need to revisit later.

It's a good thought. I went with a custom class because this is a very specific use case and I don't think it exists anywhere else. I wouldn't want to alter the site-wide small just for this one webinar case.

**Review by ryanmparrish — APPROVED** [review]

**Review by sanjayms01 — APPROVED** [review]

**Review by fullcolorcoder — APPROVED** [review]

**Pull request merged**
