### PR TITLE
[TBYB] Author franklin form block on the bacom headless page

### PR DESCRIPTION
**Pull request by arumsey**
* re-style button to use static white Spectrum pattern
* add support for hidden fields

Resolves: 

* [SITES-15861](https://jira.corp.adobe.com/browse/SITES-15861)
* [SITES-16058](https://jira.corp.adobe.com/browse/SITES-16058)

**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/swbarman/?martech=off
- After: https://headless-form--bacom--arumsey.hlx.page/drafts/swbarman/?martech=off

**Default static white button**

image

**Hover static white button**

image

**Invalid email**

image

**Success message**

image

### CODE REVIEW

**Comment by arumsey** [comment]
retest

**Review by JasonHowellSlavin — APPROVED** [review]
LGTM

**Review by meganthecoder — CHANGES_REQUESTED** [review]
Looks like the form unit tests are failing. Can you take a look?

**Review by meganthecoder — APPROVED** [review]

**Comment by meganthecoder** [comment]
Hi @arumsey , I saw two issues while I was verifying this:

1. The success message is wrong on hlx.live, but correct on hlx.page . I assume this is just due to not having published those changes. Is that correct?
2. The focus indicator on the button is hard to see in safari. I believe there should be a 3:1 contrast ratio for accessibility. Could you bump up the contrast here?
Screenshot 2023-09-19 at 11 46 15 AM

**Comment by arumsey** [comment]
> Hi @arumsey , I saw two issues while I was verifying this:
> 
> 1. The success message is wrong on hlx.live, but correct on hlx.page . I assume this is just due to not having published those changes. Is that correct?
> 2. The focus indicator on the button is hard to see in safari. I believe there should be a 3:1 contrast ratio for accessibility. Could you bump up the contrast here?
>    Screenshot 2023-09-19 at 11 46 15 AM

1. Correct. I do not have rights to publish so was only able to preview the XLSX which contains all the data.
2. I was following the Spectrum CSS static white spec for a Button (https://opensource.adobe.com/spectrum-css/button-staticcolor.html#staticwhite) but can change if you want.

**Comment by meganthecoder** [comment]
@arumsey From what I see in the XD, the static white button should look like this for focus
Screenshot 2023-09-19 at 12 45 17 PM

**Comment by arumsey** [comment]
> @arumsey From what I see in the XD, the static white button should look like this for focus Screenshot 2023-09-19 at 12 45 17 PM

Got it! I'll add a border when the Button is navigated to via keyboard navigation.

**Comment by arumsey** [comment]
@meganthecoder Actually, what you are suggesting doesn't match any other buttons on the `bacom` site. All other buttons just use the default browser focus ring and not the spectrum styled focus ring.

image

Since this appears to be the first example of a static white button on your site and since you're not fully following Spectrum patterns I guess I can make the hover color whatever you want.

**Comment by arumsey** [comment]
The CTA buttons don't use transparency but are also pretty subtle.

image

vs.

image

**Comment by meganthecoder** [comment]
@arumsey The buttons coming from milo should be following consonant. Is there a reason you didn't want to use the milo button styles we have available? https://milo.adobe.com/docs/authoring/button-mapping

**Comment by arumsey** [comment]
Good point. I inherited this branch but will make changes to use the exiting milo `.con-button` classes instead of creating duplicate styles.

**Comment by arumsey** [comment]
@meganthecoder The form block is now using `con-button` styles. I also removed background color from the form since the section should determine the background color.

image

**Review by meganthecoder — APPROVED** [review]
LGTM! Thanks for making those updates

**Pull request merged**
