### PR TITLE
MWPW-142394: Enable repo-sync for graybox

### PR DESCRIPTION
**Pull request by sukamat**
Resolves: [MWPW-142394](https://jira.corp.adobe.com/browse/MWPW-142394)

### CODE REVIEW

**Review by JasonHowellSlavin — APPROVED** [review]

**Comment by meganthecoder** [comment]
@sukamat We've adopted the milo stage rules, so you'll need to change your base branch to `stage`

**Comment by sukamat** [comment]
@meganthecoder Updated

**Review by Brandon32 — APPROVED** [review]

**Comment by meganthecoder** [comment]
@sukamat Looks good! Since we're almost at the RCP, we'll wait to merge and pick it back up next week.

**Comment by sukamat** [comment]
@meganthecoder Sounds good. Next week works for me. Thank you!

**Review by sirivuri — APPROVED** [review]

**Pull request merged**
